### ISSUE TITLE
[Feature]: Results should indicate the AI provider used

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#109]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

```
❯ kubectl get results -A
NAMESPACE                NAME         BACKEND               AGE
k8sgpt-operator-system   foocharlie       azureopenai           4h25m
k8sgpt-operator-system   foocharlie7445dfdcdbnvvmv  openai 10m
```

Adding the backend would be a really nice little convenience 

### Benefits

It opens up the potential to using multiple backends together

**Comment by TylerGillson** [comment]
Completed in #114
