### ISSUE TITLE
[Question]: May I know how to configure the anonymous and language parameters in k8sgpt-operator?

### ISSUE THREAD

**Issue by yangy30** [k8sgpt-ai/k8sgpt-operator#128]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.0.16

### Kubernetes Version

v1.24

### Host OS and its Version

CentOS 7.9

### Steps to reproduce

kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  model: gpt-3.5-turbo
  backend: openai
  noCache: false
  version: v0.3.0
  enableAI: true
  secret:
    name: k8sgpt-sample-secret
    key: openai-api-key
  baseUrl: https://api.openai.com/v1
EOF

### Expected behaviour

I have set the baseUrl parameter above, and I would also like to know how to set the anonymize and language parameters.

**Comment by AlexsJones** [comment]
These are not yet implemented, but lets keep this issue open so we can tell you when its possible

**Comment by bradmccoydev** [comment]
I am also interested in this.

**Comment by arbreezy** [comment]
it's a small change I believe, I will have a look soon
