### ISSUE TITLE
[Feature]: Install k8sgpt-overview and servicemonitor in the namespace where kube-prometheus is located

### ISSUE THREAD

**Issue by yangy30** [k8sgpt-ai/k8sgpt-operator#131]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

I must install k8sgpt and Prometheus in the same namespace, otherwise the monitor will not work 

### Solution Description

If only you could add a few helm parameters

### Benefits

This eliminates the need to install k8sgpt and prometheus in the same namespace

**Comment by arbreezy** [comment]
hey @yangy30 , what version of the prometheus operator are you using?
from prom operator: [Namespace "limits"/things to keep in mind](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/running-exporters.md#namespace-limitsthings-to-keep-in-mind)

**Comment by arbreezy** [comment]
we can definitely use the `namespaceSelector:`   and expose the value in values.yaml
feel free to open a PR @yangy30 !

**Comment by yangy30** [comment]
May I inquire if there were any modifications to the Grafana dashboard that you might have overlooked, sir?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "k8sgpt-ai/k8sgpt-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月31日(星期三) 晚上6:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [k8sgpt-ai/k8sgpt-operator] [Feature]: Install k8sgpt-overview and servicemonitor in the namespace where kube-prometheus is located (Issue #131)





 
we can definitely use the namespaceSelector:   and expose the value in values.yaml
 feel free to open a PR @yangy30 !

**Comment by arbreezy** [comment]
Hey @yangy30 just addressed the prometheus Service Monitor, I didn't touch the Grafana configMap, can you open a new issue for that one please?

**Comment by yangy30** [comment]
I have applied. Thank you for your efforts.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "k8sgpt-ai/k8sgpt-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月1日(星期四) 上午7:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [k8sgpt-ai/k8sgpt-operator] [Feature]: Install k8sgpt-overview and servicemonitor in the namespace where kube-prometheus is located (Issue #131)





 
Hey @yangy30 just addressed the prometheus Service Monitor, I didn't touch the Grafana configMap, can you open a new issue for that one please?
