### ISSUE TITLE
[Bug]: 401 unauthorized when setting LocalAi as bachend with k8sgpt-operator

### ISSUE THREAD

**Issue by eyalsofer** [k8sgpt-ai/k8sgpt-operator#141]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.0.16

### Host OS and its Version

Ubunto

### Steps to reproduce

1. Run LocalAi on kubernetes cluster (aks) 
2. configure k8sgpt-operator with localAi as backend. 
3. Get 401 Err: "Finished Reconciling K8sGPT with error: failed to call Analyze RPC: rpc error: code = Unknown desc = failed while calling AI provider localai: error, status code: 401, message: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys"

### Expected behaviour

auth is optional so its shouldnt fail over it.
same works with k8sgpt cli and LocalAi locallyl.

**Comment by TylerGillson** [comment]
@eyalsofer can you please share your K8sGPT custom resource and your LocalAI deployment details, i.e., which namespace is it in and have you verified that it is working via port-forward?

**Comment by eyalsofer** [comment]
Hi @TylerGillson ,
ok i see now where the issue could be.
i haven't noticed that the k8sgpt-config.yaml for LocalAi use default namesapce, and i installed the helm chart in k8sgpt-operator-system, and the crd config use the default ns. (the doc is a bit misleading here..) 
i will fix this and check again.
do they need to run in the same namespace? the k8s-gpt operator and localAi deployment? assuming not but just checking.

**Comment by TylerGillson** [comment]
Ok, cool, sounds good @eyalsofer. They do not have to be in the same namespace. You just have to ensure that the value of `baseUrl` in your K8sGPT resource is a properly constructed [DNS name](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services) for the LocalAI Service. Additional details [here](https://github.com/k8sgpt-ai/k8sgpt-operator/issues/132#issuecomment-1577307256).

**Comment by eyalsofer** [comment]
ok @TylerGillson ,
i have used the default k8sgtp config object for Local Ai, i don't see a baseurl field:
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
  namespace: default
spec:
  model: gpt-3.5-turbo
  backend: localai
  noCache: false
  version: v0.3.0
  enableAI: true
EOF

**Comment by TylerGillson** [comment]
Apologies about that @eyalsofer, the example in the README needs to be updated. We will get on that ASAP. Meanwhile, does configuring baseUrl resolve your issue?

**Comment by eyalsofer** [comment]
@TylerGillson @arbreezy  Thanks fpr the fast fix.
No, still having the issue. 
i found an open issue on the same matter at localAi github: https://github.com/go-skynet/LocalAI/issues/471

**Comment by TylerGillson** [comment]
@eyalsofer I validated K8sGPT + LocalAI yesterday using a kind cluster and did not face any issues. You may find the discussion on https://github.com/k8sgpt-ai/k8sgpt-operator/issues/132 helpful.

Please feel free to ping me on the K8sGPT community Slack and I would be happy to take a look at your env with you.
