### ISSUE TITLE
[Bug]: k8sgpt-deployment is not synchronized, after k8sgptConfig update

### ISSUE THREAD

**Issue by fyuan1316** [k8sgpt-ai/k8sgpt-operator#173]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.8

### Kubernetes Version

v1.25.6

### Host OS and its Version

ubuntu

### Steps to reproduce

1. create a k8sGPT CR with a invalid baseUrl, say 
```bash
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
  namespace: default
spec:
  ai:
    enabled: true
    model: ggml-gpt4all-j
    backend: localai
    baseUrl: http://local-ai.local-ai.svc.cluster.local:8080/v1
  noCache: false
  version: v0.3.8
EOF
```
2. check operator log

<img width="1662" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt-operator/assets/42265657/9a62f163-131a-4638-8818-dd97e7d61fb6">

3. fix baseUrl to `http://local-ai.local-ai.svc.cluster.local/v1`
<img width="1213" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt-operator/assets/42265657/acff66ae-b12d-49bf-8354-770abe9f8025">

4. check operator & deployment logs
> operator log 
<img width="1672" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt-operator/assets/42265657/d4fbd2ef-feba-45e6-8966-3a59e478213b">

> deployment log
<img width="1671" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt-operator/assets/42265657/944a4616-e624-4478-abf1-65d6d2fcced6">

### Expected behaviour

k8sGPT-deployment should use the latest configuration after the K8sGPT CR changes

### Actual behaviour

The k8sGPT-deployment configuration has not been updated with the latest configuration after the K8sGPT CR changes

**Comment by fyuan1316** [comment]
I thought I could try to fix it 😄

**Comment by AlexsJones** [comment]
Thanks for reporting the issue and having a go - I will take a look at the PR!

**Comment by wujunwei** [comment]
same issue here !
