### ISSUE TITLE
[Bug]: container "manager" in pod "release-k8sgpt-operator-controller-manager-xxx-xxx is waiting to start: trying and failing to pull image

### ISSUE THREAD

**Issue by eravindar12** [k8sgpt-ai/k8sgpt-operator#176]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Steps to reproduce

 k logs -f release-k8sgpt-operator-controller-manager-xxx-xxx -n k8sgpt-operator-system
**Error from server (BadRequest): container "manager" in pod "release-k8sgpt-operator-controller-manager-675c7f8bf-4rkpk" is waiting to start: trying and failing to pull image**

### Expected behaviour

container needs to up and running and able to pull the image

**Comment by arbreezy** [comment]
hey @eravindar12 could you share more information about the version of the helm chart and if you are setting any values when deploying that chart?
