### ISSUE TITLE
[Feature]:  Add integrations support in the operator

### ISSUE THREAD

**Issue by arbreezy** [k8sgpt-ai/k8sgpt-operator#179]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

Feature parity with K8sGPT current implementation:

More specifically, the operator at the moment doesn't support the integrations feature (trivy).

Recently we introduced in k8sgpt cli a `no-install` [subfeature](https://github.com/k8sgpt-ai/k8sgpt/blob/main/cmd/integration/activate.go#L58) in the integrations which effectively won't install Trivy.

### Solution Description

K8sGPT CR will have a new `integrations` section to support this feature which will not install integrations but **assume** they are already installed 
e.g trivy operator is already deployed to a K8s cluster that K8sGPT operator is running

example CR:
```yaml
...  
integrations:
  trivy:
    enabled: true
...
  ```

### Benefits

Feature parity with K8sGPT and ability to extend integrations support in the future

**Comment by eyalsofer** [comment]
@arbreezy - please assign me on this.

**Comment by eyal-sofer** [comment]
please assign me

**Comment by AlexsJones** [comment]
This is dependent on the configuration API work
@eyal-sofer how are you intending to do this?

**Comment by wujunwei** [comment]
If no one has started solving it yet, I will finish it by next Monday.

**Comment by wujunwei** [comment]
I  find three ways to Implement this：
1.  need some changes in project `k8sgpt-ai/k8sgpt` add `env` or config to install  `trivy` when server start.
2.  we can install helm chart in `k8sgpt-operator` directly and set active_filters in server's config file in a **init container**.
3. Do it by grpc client , add new method `active filter`.

**Comment by arbreezy** [comment]
hey @wujunwei ,  

firstly, I can assign it to you if you want and thanks for showing interest in the project !
 re: 2. I believe is better to not install anything directly to the cluster from the operator and assume trivy is already running, maybe a check if operator can find trivy's [workload](https://github.com/k8sgpt-ai/k8sgpt/blob/main/pkg/integration/trivy/trivy.go#L99) in a cluster.
 
Installing or not,  integration charts like trivy, GRPC new methods will be required to interact with K8sGPT integrations handler

**Comment by AlexsJones** [comment]
We are very close to this being possible now configuration API has been merged in

https://github.com/k8sgpt-ai/k8sgpt-operator/pull/201

**Comment by AlexsJones** [comment]
This is a WIP https://github.com/k8sgpt-ai/k8sgpt-operator/pull/225
