### ISSUE TITLE
[BUG]: LocalAi returns connection refused to k8sgpt-operator 

### ISSUE THREAD

**Issue by eyalsofer** [k8sgpt-ai/k8sgpt-operator#189]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

V3.0.9

### Steps to reproduce

1. deploy local-ai chart with the default configuration as detailed here: https://github.com/go-skynet/helm-charts - latest version V2.1.0
2. deploy k8sgpt-operator helm chart - latest version V0.0.19.
3. apply k8sgpt-config.yaml with localai base url configured to port 80:
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
  namespace: default
spec:
  ai:
    enabled: true
    model: ggml-gpt4all-j
    backend: localai
    baseUrl: http://local-ai.local-ai.svc.cluster.local/v1
  noCache: false
  version: v0.3.9
  4. after applying you will start to see this err in localAi logs: 
  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:37005: connect: connection refused"
  

### Expected behaviour

no errors in local-ai, and scan results from k8sgpt

**Comment by eyalsofer** [comment]
@AlexsJones FYI

**Comment by galfrylich** [comment]
i have the same problem... tried to change the baseUrl with no success

**Comment by AlexsJones** [comment]
We have spent multiple hours trying to reproduce this and the current advice is this:

Use operator version 0.0.20
K8sgpt version 0.3.8 or higher.

It's important to be aware that you will need to make the baseURL work for the namespace you have deployed `local-ai` in.

Please let me know if this is still an issue
