### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error

### ISSUE THREAD

**Issue by Crystalyyy** [k8sgpt-ai/k8sgpt-operator#195]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.0.20

### Kubernetes Version

v1.16.9

### Steps to reproduce

When I install operator, it fails with error: standard_init_linux.go:211: exec user process caused "exec format error

### Expected behaviour

Successful installation

### Actual behaviour

When I install operator, it fails with error: standard_init_linux.go:211: exec user process caused "exec format error

**Comment by AlexsJones** [comment]
What arch are you on?

**Comment by arbreezy** [comment]
K8s version is pretty old  `v1.16.9`
