### ISSUE TITLE
[Bug]: Chart v0.0.4 and v0.0.5 were not published

### ISSUE THREAD

**Issue by InputObject2** [k8sgpt-ai/k8sgpt-operator#20]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.0.3

### Steps to reproduce

Installing the chart does not work as it helm cannot find it:

```bash
helm install k8sgpt/k8sgpt-operator  --version 0.0.5
```

Searching for the chart reveals only the v0.0.3 chart

```bash
helm search repo k8sgpt-operator

NAME                    CHART VERSION   APP VERSION     DESCRIPTION
k8sgpt/k8sgpt-operator  v0.0.3          0.1.0           A Helm chart for Kubernetes
```

### Expected behaviour

v0.0.5 chart should exist.

### Actual behaviour

Charts after 0.0.3 have not been released.

**Comment by AlexsJones** [comment]
Absolutely right, sorry for this, it's a workflow issue and we will resolve shortly

**Comment by thschue** [comment]
We will change the workflow soon and centralize helm charts. See here: https://github.com/k8sgpt-ai/community/issues/25
