### ISSUE TITLE
[Question]: Should there be a Scan Frequency?

### ISSUE THREAD

**Issue by theblinkingusb** [k8sgpt-ai/k8sgpt-operator#211]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.14

### Kubernetes Version

v1.26

### Steps to reproduce

1. Deploy k8s operator using helm
2. Add K8sGPT CRD with openai backend (for v0.3.14)

After deployment we hit a couple hundred API calls / hour

### Expected behaviour

I can see many teams appreciating the constant scan, especially those with monitors in Prom/Grafana; however, this can likely increase costs for some.

Possibly the introduction of a cron like scan frequency to allow the user to choose how frequently they need an AI assisted audit.
Or notes in the docs where the expectation would be for the user to install/uninstall the application when they needed scans.

### Actual behaviour

Appears to be constant scanning 

### Additional Information

Searched around docs, GIT, reddit, YT, and Slack - apologies if this was already discussed somewhere

**Comment by arbreezy** [comment]
We could potentially enable users control the intervals between reconciliation loops without touching the k8sgpt deployment.

Another alternative may be checking if we get any new errors from analysers and only then enable the `explain` in k8sgpt to go and fetch the ai backend response. This approach could be enabled by  bidirectional grpc streams..

Any more ideas @AlexsJones ?

**Comment by arbreezy** [comment]
@theblinkingusb what you can do as an alternative is switching off the `explain` attribute which will prevent making calls to AI backends. Obviously you will not get any possible solutions in your Result Custom Resources

**Comment by theblinkingusb** [comment]
Thanks @arbreezy - I just made that change. This is nice too because it keeps the grafana dashboards populated for forensics (vs doing the helm uninstall/reinstall as I was before). Perhaps I can throw a simple patch script on a cron every week or two. 
I'll close this out for now!

**Comment by arbreezy** [comment]
@theblinkingusb no worries.
We can expose to the user (helm chart's values.yaml -- overriding  a value) the interval time between reconciliation loops of the operator. It's a rather small change to make but I am not sure how much it would make sense, eager to get your thoughts :)
