### ISSUE TITLE
[Question]: May I modify the address of the image "ghcr. io/k8sgpt ai/k8sgpt: v0.3.8"?

### ISSUE THREAD

**Issue by yangy30** [k8sgpt-ai/k8sgpt-operator#212]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.0.21

### Kubernetes Version

v1.26.8

### Host OS and its Version

rockylinux 8.8

### Steps to reproduce

``k describe pod k8sgpt-deployment-76ffb88d89-pjjfs``
```shell
  Normal  Scheduled  2m13s  default-scheduler  Successfully assigned monitoring/k8sgpt-deployment-76ffb88d89-pjjfs to k8s-node01
  Normal  Pulling    2m12s  kubelet            Pulling image "ghcr.io/k8sgpt-ai/k8sgpt:v0.3.8"
```

### Expected behaviour

May I modify the address of the image "ghcr. io/k8sgpt ai/k8sgpt: v0.3.8"?

**Comment by arbreezy** [comment]
In your K8sGPT CR you can specify which version of k8sgpt you want to run in the cluster

**Comment by yangy30** [comment]
```shell
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
  namespace: default
spec:
  .....................................................................
  // version: v0.3.8
  version: ghcr.dockerproxy.com/k8sgpt-ai/k8sgpt:v0.3.8
  .....................................................................
EOF
```
May I ask if this is how the modification was made？ @arbreezy

**Comment by arbreezy** [comment]
You can only define the container's image tag not the repository path.

The k8sgpt version reflects the release versions of k8sgpt [repo](https://github.com/k8sgpt-ai/k8sgpt/releases)

**Comment by yangy30** [comment]
My network environment cannot pull images. Is there any way to modify the address of this image? @arbreezy

**Comment by arbreezy** [comment]
Hey @yangy30 , it's indeed hardcoded at the moment and is not possible to modify it.

Can you try a proxy setup or something similar in the meantime?

**Comment by yangy30** [comment]
好的，以后如果有时间是否可以实现自定义镜像，比如加一个判断，如果version参数为全地址时不使用默认镜像？ @arbreezy

**Comment by arbreezy** [comment]
@yangy30, sounds good to me, feel free to open a Feature GH issue; I will close the Question now
