### ISSUE TITLE
LocalAi integration not working  with k8sgpt-operator

### ISSUE THREAD

**Issue by harshsing2891** [k8sgpt-ai/k8sgpt-operator#214]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v.0.3.8

### Kubernetes Version

1.24

### Host OS and its Version

linux

### Steps to reproduce

1.deploy local-ai chart with the default configuration as detailed here: https://github.com/go-skynet/helm-charts - latest version V2.1.0
2. deploy k8sgpt-operator helm chart - latest version V0.0.21
3. apply k8sgpt-config.yaml with localai base url configured to port 80:
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
name: k8sgpt-local-ai
namespace: default
spec:
ai:
enabled: true
model: ggml-gpt4all-j
backend: localai
baseUrl: http://local-ai.local-ai.svc.cluster.local/v1
noCache: false
version: v0.3.8

### Expected behaviour

integration should work as it is working with azureopen ai

**Comment by arbreezy** [comment]
Hey @harshsing2891 can you share some logs whilst also making sure that the local's ai endpoint is reachable from k8sgpt's pod.
