### ISSUE TITLE
[Feature]: create Grafana-Dashboard CR optionally

### ISSUE THREAD

**Issue by jkleinlercher** [k8sgpt-ai/k8sgpt-operator#220]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

This issue is very similar to https://github.com/kyverno/kyverno/pull/7992 . When using the grafana-operator, the grafana-dashboards should be defined in special Grafana-Dashboard CRs and not just a ConfigMap.
So it would be great if the Helm-Charts creates also a Grafana-Dashboard CR and referenced to the ConfigMap (opt-in).

### Solution Description

very similar to https://github.com/kyverno/kyverno/pull/7992

### Benefits

User who have the grafana-operator deployt get automatically the K8sGPT Grafana Dashboard.

**Comment by arbreezy** [comment]
Good shout, I see many people shifting to CRs so I echo the same, we should add support in our helm values file.

**Comment by jkleinlercher** [comment]
@arbreezy better late than never - now I created PR #322 for a review, if you like to!
