### ISSUE TITLE
[Feature]: Migrate all RBAC related resources to Helm chart's templates

### ISSUE THREAD

**Issue by arbreezy** [k8sgpt-ai/k8sgpt-operator#259]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

Both manager's and k8sgpt's roles have to match in order for the former to grant permissions to K8sgpt cluster role or add the verb `escalate`. Following the Least privileged access idiom, would be great if we move away from the existing way of managing roles

### Solution Description

Lift and shift the cluster role, bindings and service account from operator's code to Helm chart's tempates

### Benefits

To be more transparent to the end users and also avoid situations like K8s API [restrictions](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-creation-or-update) with roles which caused issues in the latest `v0.0.22`

**Comment by MateSousa** [comment]
hi @arbreezy, can i do ?

**Comment by MateSousa** [comment]
hey @arbreezy, just to make sure I got it right, i need to migrate all the RBAC from this folder `config/rbac` to the helm template, right?

**Comment by arbreezy** [comment]
Hello @MateSousa let me elaborate a bit more,

At the moment we are creating with the controller the K8sGPT's [role](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/pkg/resources/k8sgpt.go#L137), [rolebinding](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/pkg/resources/k8sgpt.go#L102) and service account.

There are two issues with this approach,

1. The controller's role we define here has to match the K8sGPT's role permissions otherwise K8s API disallow the creation, although controller doesn't need those perms for its own workload
2. In terms of readability, we want to surface those K8sGPT;s role rolebinding and service account in the chart

So the proposed solution is to move them out of our codebase and include them as part of the chart's template [folder](https://github.com/k8sgpt-ai/k8sgpt-operator/tree/main/chart/operator/templates)
then in the deployment [struct](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/pkg/resources/k8sgpt.go#L207) we will just reference the service account name (as we already do)
