### ISSUE TITLE
[Feature]: Labeled results.core.k8sgpt.ai resources

### ISSUE THREAD

**Issue by prometherion** [k8sgpt-ai/k8sgpt-operator#263]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

The `Result` objects, when generated, are not labeled.

If using labels, it would be interesting to get more data about the `k8sgpt` resource who generated it, as well as other important information, such as the `Deployment` who generated it.

### Benefits

The basic idea is to take full advantage of the label selection offered by Kubernetes, simplifying the selection of `Result` instances generated by a specific driver.

e.g.:

```
kubectl get results.core.k8sgpt.ai -l k8sgpts.k8sgpt.ai/name=k8sgpt-sample
kubectl get results.core.k8sgpt.ai -l k8sgpts.k8sgpt.ai/backend=openapi
```

**Comment by prometherion** [comment]
I'm happy to work on this, by providing a PR.

**Comment by prometherion** [comment]
JFI I marked the k8sgpt Slack discussion as completed although it's not, since I'm not able to join the Slack channel since it's open only to `k8sgpt.ai` domains.

**Comment by arbreezy** [comment]
> JFI I marked the k8sgpt Slack discussion as completed although it's not, since I'm not able to join the Slack channel since it's open only to `k8sgpt.ai` domains.


hmm that's odd @prometherion , we 'll have a look
