### ISSUE TITLE
[Feature]: add k8sgpt image in operator k8sgpt crd

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/k8sgpt-operator#268]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

k8sgpt crd has k8sgpt image tag as `version` but not image name.
image name is hard coded in controller, [k8sgpt.go](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/1ca833b8d1dea5e8cdba3e97bf4f49bce1ffb690/pkg/resources/k8sgpt.go#L212)

### Solution Description

set image name in crd and set default value as hard coded value
override crd value in k8sgpt.go

### Benefits

users can use their own version of k8sgpt.

**Comment by arbreezy** [comment]
Do you want to pick this up @JuHyung-Son ?
It's a small change in the CR and K8sGPT deployment spec

**Comment by JuHyung-Son** [comment]
yes i will pick this up

**Comment by JuHyung-Son** [comment]
by the way, is this cr autogenerated? or manually updated?
https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/config/crd/bases/core.k8sgpt.ai_k8sgpts.yaml

**Comment by arbreezy** [comment]
Is handled by `make manifests`  but the chart's crd templares are manually edited at the moment

**Comment by arbreezy** [comment]
I also suggest to not introduce any breaking changes in the CR of K8sGPT and retain version attribute

**Comment by JuHyung-Son** [comment]
i see.
then keep the `Version` and make `Image` optional?

**Comment by arbreezy** [comment]
Yes, regarding the image you can even set a kubebuilder marker with default value to k8sgpt's registry repo

**Comment by arbreezy** [comment]
@JuHyung-Son agreed it's a common convention to use this struct but unless we create a webhook to convert this `version` to `image.tag` this could introduce breaking changes to existing users with K8sGPT CRs

duplicating `tag` and `version` becomes even more convoluted for no reason I believe..

My suggestion is to keep `version` and add another top level spec attribute `repository` so we don't break compatibility between versions and you can use your own registry.

**Comment by JuHyung-Son** [comment]
thanks for suggestion.
i request pr. please check
