### ISSUE TITLE
[Feature]: add imagePullSecret to k8sgpt crd spec

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/k8sgpt-operator#280]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

from this [pr](https://github.com/k8sgpt-ai/k8sgpt-operator/pull/272) users can use other repositories (e.g. their own image) but imagePullSecrets does not added, so that user cannot use private repository.

### Solution Description

add imagePullSecret name. and if it is given, add it k8sgpt serviceaccount `imagePullSecret`.

### Benefits

users can use private repository

**Comment by hfiorillo** [comment]
hey @AlexsJones I'd like to pick this up if possible. I can't join the slack channel to discuss using my email, if you could send over an invite that would be great!

**Comment by JuHyung-Son** [comment]
@hfiorillo this is on review 

https://github.com/k8sgpt-ai/k8sgpt-operator/pull/282
