### ISSUE TITLE
feature: Help wanted, updating the Result status field to show more information

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#3]
<img width="1213" alt="Screenshot 2023-04-24 at 17 23 06" src="https://user-images.githubusercontent.com/1235925/234042373-cdd38656-fe29-4a4c-8c67-158589b1e310.png">

**Comment by arbreezy** [comment]
I can have a look @AlexsJones :)

**Comment by rakshitgondwal** [comment]
Are you working on this?@arbreezy 
If no, then I can take this up.

**Comment by AlexsJones** [comment]
I think a good start would be to describe the resource type e.g.

NAMESPACE NAME AGE KIND

**Comment by arbreezy** [comment]
I picked a different piece of work first,  feel free to start working on it @rakshitgondwal :)

**Comment by arbreezy** [comment]
any updates @rakshitgondwal , do you need any help?

**Comment by AlexsJones** [comment]
I would assume this is open for anyone to do.

**Comment by rakshitgondwal** [comment]
Hey @arbreezy, Actually my exams are going right now, so I am not really getting any time. So sorry for not updating!

**Comment by TylerGillson** [comment]
@AlexsJones, @rakshitgondwal, @arbreezy I can take this one and #109. Can have something by EOD.
