### ISSUE TITLE
[Bug]: Wrong deployment image processing 

### ISSUE THREAD

**Issue by ultram4rine** [k8sgpt-ai/k8sgpt-operator#346]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.8

### Kubernetes Version

v1.28.0

### Steps to reproduce

Include port in repository in `K8sGPT` object like `<host>:<port>/<path>/<image>`.

### Expected behaviour

Operator will create a deployment with normal image.

### Actual behaviour

Operator will turn image in `<host>:<tag>`, thus result into `ImagePullBackOff`.

### Additional Information

I've found the lines were this happens:
https://github.com/k8sgpt-ai/k8sgpt-operator/blob/db04fbdf23bdeeaa1053af1f578a7f3bcf7e0ca0/controllers/k8sgpt_controller.go#L168-L180

Quick solution is to parse image like this:
```go
image := strings.Split(imageURI, ":")
if len(image) == 2 {
	imageRepository = image[0]
	imageVersion = image[1]
} else {
	imageRepository = fmt.Sprintf("%s:%s", image[0], image[1])
	imageVersion = image[2]
}
```
or
```go
image := strings.Split(imageURI, ":")

imageRepository := strings.Join(image[0:len(image)-1], ":")
imageVersion := image[len(image)-1]
```

Possible better solution is to use maybe `net/url` or some other lib.

Test: https://go.dev/play/p/nIFGk2QroT5

**Comment by ultram4rine** [comment]
Btw, what is going on here: 
https://github.com/k8sgpt-ai/k8sgpt-operator/blob/db04fbdf23bdeeaa1053af1f578a7f3bcf7e0ca0/controllers/k8sgpt_controller.go#L175-L179

If image repo is not the same as in `K8sGPT` CRD, it leaves it as is and updates only version.

Maybe it should update image repo to `k8sgptConfig.Spec.Repository`?

**Comment by arbreezy** [comment]
> Btw, what is going on here:
> 
> https://github.com/k8sgpt-ai/k8sgpt-operator/blob/db04fbdf23bdeeaa1053af1f578a7f3bcf7e0ca0/controllers/k8sgpt_controller.go#L175-L179
> 
> If image repo is not the same as in `K8sGPT` CRD, it leaves it as is and updates only version.
> 
> Maybe it should update image repo to `k8sgptConfig.Spec.Repository`?

yes that looks wrong :+1:
