### ISSUE TITLE
Request to add latest k8sgpt app version in the helm operator

### ISSUE THREAD

**Issue by thamilselvam-source** [k8sgpt-ai/k8sgpt-operator#347]
Hello All,
We would like to use the K8sgpt helm operator with the google Gemini as backend. but in the latest helm charts(v 0.1.0) doesn't have latest k8sgpt app version. the current k8sgpt operator in the chart doesn't support Google as backend. Request you to kindly add or advise us to get the latest k8sgpt operator.
![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/156431098/bdaf0411-4b29-40d8-a8e9-a77bb36e68cf)

**Comment by VaibhavMalik4187** [comment]
@arbreezy, could you please assign this to me?

**Comment by thamilselvam-source** [comment]
@VaibhavMalik4187 i have tested, still doesn't support google as backend. and one more, the backend should be as google not gemini. Even I have updated the changes with google instead of gemini, wherever you made changes. but still not working

**Comment by VaibhavMalik4187** [comment]
> @VaibhavMalik4187 i have tested, still doesn't support google as backend. and one more, the backend should be as google not gemini. Even I have updated the changes with google instead of gemini, wherever you made changes. but still not working

Appreciate the feedback and testing @thamilselvam-source, I'll try to figure out the right way to do it asap.
