### ISSUE TITLE
[Question]: Can I configure on-prem s3 i.e. minio?

### ISSUE THREAD

**Issue by qdrddr** [k8sgpt-ai/k8sgpt-operator#386]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.28

### Kubernetes Version

v1.27.10

### Steps to reproduce

Question: can I configure on-prem S3 such as minio?
If yes, how do I configure it with K8sGPT (CLI) & K8sGPT Operator (Helm Values file)?

### Expected behaviour

Be able to configure non-cloud S3 bucket endpoint URL 

### Actual behaviour

Can't find how to provide URL of the bucket.

**Comment by arbreezy** [comment]
Hey @qdrddr it's not possible atm but it will be easy to expose an endpoint in k8sgpt cli and the support it in the operator.
Please open a GH issue in K8sgpt's repository to track the feature there
