### ISSUE TITLE
[Feature]: Generate results CRD in related to issue namespace

### ISSUE THREAD

**Issue by intonet** [k8sgpt-ai/k8sgpt-operator#390]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

Similar to Trivy's results will be good if the result from k8sGPT can be placed in the "client" namespace.

### Solution Description

put result in namespace where issue was found

### Benefits

this will be easy to obtain for clients limited to their namespace

**Comment by VaibhavMalik4187** [comment]
@arbreezy, I'd like to work on this issue.
