### ISSUE TITLE
[Question]: <Question Title> the Latest k8sgpt operator doesn't support google as a backend. but standalone installation (K8sGPT CLI) does support.

### ISSUE THREAD

**Issue by thamilselvam-source** [k8sgpt-ai/k8sgpt-operator#410]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.29

### Host OS and its Version

Linux

### Steps to reproduce

kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: gemini-pro
    backend: google
    secret:
      name: k8sgpt-sample-secret
      key: gemini-api-key
    # anonymized: false
    # language: english
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.29
  #integrations:
  # trivy:
  #  enabled: true
  #  namespace: trivy-system
  # filters:
  #   - Ingress
  # sink:
  #   type: slack
  #   webhook: <webhook-url> # use the sink secret if you want to keep your webhook url private
  #   secret:
  #     name: slack-webhook
  #     key: url
  #extraOptions:
  #   backstage:
  #     enabled: true
EOF

### Expected behaviour

if you apply the above yaml file, it returns as google as backend doesn't support.

**Comment by JuHyung-Son** [comment]
yes we need to add google backend in operator
