### ISSUE TITLE
[Feature]: Decrease repo size with the robot.

### ISSUE THREAD

**Issue by Aisuko** [k8sgpt-ai/k8sgpt-operator#47]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

We can add some useful bots to help me manage the repo size. Here is an example for reducing the repo size, please take a look: https://github.com/Aisuko/k8sgpt-operator/pull/1

### Benefits

Automatically help us to decrease the repo size.

### Potential Drawbacks

Of course drawbacks forward.

### Additional Information

I believe it is free to plan is ok for covering the public project.

**Comment by AlexsJones** [comment]
Thanks @Aisuko great suggestion. @thschue any remarks? Otherwise, I'll go ahead and add it.
