### ISSUE TITLE
feature: Create ArtifactHub Entry for k8sgpt-operator

### ISSUE THREAD

**Issue by bradmccoydev** [k8sgpt-ai/k8sgpt-operator#5]
Checklist:
* [x] I've searched for similar issues and couldn't find anything matching
* [x] I've discussed this feature in the #k8sgpt slack channel

## Is this feature request related to a problem?
* [ ] Yes
* [x] No

As a user of the k8sgpt-operator I would like to see this chart on ArtifactHub so I can subscribe to updates and get an email notification when there is a new version available, see the helm values easily, and see the security posture of the chart.

We can also create a badge on the repository that links to the ArtifactHub page.

Here is a blog I have done in the past explaining the process: https://blog.bradmccoy.io/linking-helm-charts-in-github-pages-to-artifacthub-46e02e19abfe

**Comment by rakshitgondwal** [comment]
Hey @bradmccoydev! I'd like to work on this.

**Comment by thschue** [comment]
@rakshitgondwal: Created a new repository for the hosting of helm charts here: https://github.com/k8sgpt-ai/charts (see: https://github.com/k8sgpt-ai/community/issues/25) will ping you as soon as I finished the publishing things and then you should be able to start.

**Comment by bradmccoydev** [comment]
let me now if you need help on this @rakshitgondwal im happy to help

**Comment by rakshitgondwal** [comment]
Sure! @thschue @bradmccoydev

**Comment by thschue** [comment]
The helm repo is finished so far (https://charts.k8sgpt.ai) github.com/k8sgpt-ai/charts

**Comment by rakshitgondwal** [comment]
Hey, @bradmccoydev! Just went through your blog and I had some questions.
- If we are using the [chart repo](github.com/k8sgpt-ai/charts) for ArtifcatHub, we'll need to create a separate gh-pages branch right?
- We already have the charts and the `index.yaml` in the repo, so do we need a GitHub Action now?
- We have setup up the custom domain to `https://charts.k8sgpt.ai/` for the static website hosted using github pages, so now this url will be used in the place of `https://<repoOwner>.github.io/<repoName>/` right?

**Comment by thschue** [comment]
Added this already as I was in the flow, done -> https://artifacthub.io/packages/helm/k8sgpt/k8sgpt-operator. The missing README is in this PR ->  https://github.com/k8sgpt-ai/k8sgpt-operator/pull/45

The only thing missing is the official publisher state, will take care of this a bit later.
