### ISSUE TITLE
chore: adding this to the `README` 

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#52]
Thanks @bradmccoydev would you mind adding this to the `README` in the table of available helm values?

_Originally posted by @AlexsJones in https://github.com/k8sgpt-ai/k8sgpt-operator/issues/51#issuecomment-1531266623_

**Comment by bradmccoydev** [comment]
PR done for this here: https://github.com/k8sgpt-ai/k8sgpt-operator/pull/55
