### ISSUE TITLE
[Feature]: Add unit tests into GH check

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#53]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

In order to improve our visibility on any issues, we should take the `go test ./...` results as a metric for PR/branch health by adding them into GH checks. 

### Benefits

This would improve our frequency of testing and add a quality gate.

**Comment by rakshitgondwal** [comment]
Hey @AlexsJones, can you please help me out here?

**Comment by AlexsJones** [comment]
Yes, apologies for the delay, it was added by @thschue  prior to me commenting
