### ISSUE TITLE
Bug: Grafana Dashboard number of results

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#584]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

latest

### Kubernetes Version

latest

### Host OS and its Version

ubuntu

### Steps to reproduce

1. Have an existing set of K8sGPT results
2. Start the operator with grafana dashboard + service monitor enabled
3. View that the dashboard is missing k8sgpt_results_by_type

### Expected behaviour

There is a graph that should populate

### Actual behaviour

Missing data

### Additional Information

The code will only increment the counter on raw results processing
```
		if operation == resources.CreatedResult {
			numberOfResultsByType := instance.r.MetricsBuilder.GetCounterVec("k8sgpt_number_of_results_by_type")
			if numberOfResultsByType != nil {
				numberOfResultsByType.WithLabelValues(result.Spec.Kind, result.Spec.Name, instance.k8sgptConfig.Name).Inc()
			} else if operation == resources.UpdatedResult {
				instance.logger.Info("updated successfully %s", result.Name)
			}
		}
```

**Comment by Yadavanurag13** [comment]
I want to pick this issue. @AlexsJones

**Comment by AlexsJones** [comment]
Go for it @Yadavanurag13 I linked the code that needs modifying, it's in the pre-analysis step in the controller pkg!

**Comment by vihaan-that** [comment]
Dear @AlexsJones  If the bug is still up for grabs, I would like to take a chance at solving it, however I am new to this project, and I would appreciate any pointers I can get to close the bug. 

Thank you

**Comment by AlexsJones** [comment]
This has been fixed https://github.com/k8sgpt-ai/k8sgpt-operator/pull/585

**Comment by vihaan-that** [comment]
I would like to be a recurring contributor for this repo, and looking at your code fix vs what I had planned in my mind makes me reflect on the knowledge gap that I have, I would like to know if there's any resources you would recommend to be a better contributor.

**Comment by AlexsJones** [comment]
> I would like to be a recurring contributor for this repo, and looking at your code fix vs what I had planned in my mind makes me reflect on the knowledge gap that I have, I would like to know if there's any resources you would recommend to be a better contributor.

I would become familiar with Kubebuilder, golang and the prometheus metrics SDK as a start. Good luck!
