### ISSUE TITLE
ROADMAP: Observability included

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#60]
- Grafana Dashboards and configuration as part of the Operator start up

**Comment by arbreezy** [comment]
I started some work on the Dashboards [here](https://github.com/k8sgpt-ai/k8sgpt-operator/pull/65)

**Comment by arbreezy** [comment]
Do we have more outstanding features for this Roadmap item?

**Comment by arbreezy** [comment]
closing the Roadmap GH issue since it's completed
