### ISSUE TITLE
question: strange logs + missing usage information

### ISSUE THREAD

**Issue by antongisli** [k8sgpt-ai/k8sgpt-operator#7]
Checklist:

* [x ] I've searched for similar issues and couldn't find anything matching
* [ x] I've included steps to reproduce the bug.
* [ ] I've included the version of Kubernetes and k8sgpt.

### Subject of the issue

error storing value to cache: open /home/nonroot/.cache/k8sgpt/openai

### Your environment

K8s 1.24 (vanilla)
Ubuntu 20.04

### Steps to reproduce

Install k8sgpt operator using the README, added valid openai key.

### Expected behaviour
not sure to be honest

### Actual behaviour

as I don't know how to use this, how to collect outputs or direct them to any particular prometheus server, etc., I checked the logs on the pod and found many messages like this in the log:
`error storing value to cache: open /home/nonroot/.cache/k8sgpt/openai-<snip>gc3RhdHVzLg==: file name too long
`
I also see what looks like successfull http 200 messages from, presumably, the openai API:
`{"level":"info","ts":1682506122.1083932,"msg":"request completed","duration_ms":63152,"method":"GET","remote_addr":"100.72.70.84:45874","status_code":200,"url":"/analyze"}`

I don't know if the installation is working correctly or not, nor can I figure out how to see the outputs of the analyses.

**Comment by AlexsJones** [comment]
Can you show us your `K8sGPT` custom resource? 
Typically that issue is from an older `k8sgpt` CLI version being set in that object.

**Comment by antongisli** [comment]
here's the CRD:
```
kubectl get crd k8sgpts.core.k8sgpt.ai -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-04-26T09:13:25Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: k8sgpts.core.k8sgpt.ai
  resourceVersion: "6077357"
  uid: a4e9b551-a06d-4cb8-b46d-bc86d508b37e
spec:
  conversion:
    strategy: None
  group: core.k8sgpt.ai
  names:
    kind: K8sGPT
    listKind: K8sGPTList
    plural: k8sgpts
    singular: k8sgpt
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: K8sGPT is the Schema for the k8sgpts API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: K8sGPTSpec defines the desired state of K8sGPT
            properties:
              backend:
                type: string
              enableAI:
                type: boolean
              model:
                type: string
              namespace:
                type: string
              noCache:
                type: boolean
              secret:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                type: object
              version:
                type: string
            type: object
          status:
            description: K8sGPTStatus defines the observed state of K8sGPT
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: K8sGPT
    listKind: K8sGPTList
    plural: k8sgpts
    singular: k8sgpt
  conditions:
  - lastTransitionTime: "2023-04-26T09:13:25Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-04-26T09:13:25Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1

```

**Comment by AlexsJones** [comment]
Rather than the CRD if you could produce the CR that would help. 
A command like `kubectl get k8sgpt -o json` might be sufficient. 

Also ( and this is more just an FYI ) we have updated the getting-started docs [here](https://docs.k8sgpt.ai/getting-started/in-cluster-operator/)

**Comment by antongisli** [comment]
Thanks for that. Here is the CR:
`{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "core.k8sgpt.ai/v1alpha1",
            "kind": "K8sGPT",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"core.k8sgpt.ai/v1alpha1\",\"kind\":\"K8sGPT\",\"metadata\":{\"annotations\":{},\"name\":\"k8sgpt-sample\",\"namespace\":\"default\"},\"spec\":{\"backend\":\"openai\",\"enableAI\":true,\"model\":\"gpt-3.5-turbo\",\"namespace\":\"default\",\"noCache\":false,\"secret\":{\"key\":\"openai-api-key\",\"name\":\"k8sgpt-sample-secret\"},\"version\":\"v0.2.7\"}}\n"
                },
                "creationTimestamp": "2023-04-26T09:15:53Z",
                "finalizers": [
                    "k8sgpt.ai/finalizer"
                ],
                "generation": 2,
                "name": "k8sgpt-sample",
                "namespace": "default",
                "resourceVersion": "6078939",
                "uid": "380dd8ca-6204-47d3-bc57-e952664c73b2"
            },
            "spec": {
                "backend": "openai",
                "enableAI": true,
                "model": "gpt-3.5-turbo",
                "namespace": "default",
                "secret": {
                    "key": "openai-api-key",
                    "name": "k8sgpt-sample-secret"
                },
                "version": "v0.2.7"
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": ""
    }
}
`
I'll check out the updated getting started docs, cheers.

**Comment by antongisli** [comment]
`kubectl get results -o json | jq .`
did the trick. I  can see results there which look accurate. I still have the errors in the log e.g. `error storing value to cache: open /home/nonroot/.cache/k8sgpt/openai` but it doesn't seem to interfere with the results.

I'm interested in how we can connect this thing to things like alertmanager or surface these directly in Palette.

**Comment by AlexsJones** [comment]
Well in `v0.0.3` there is an integrated `SerivceMonitor` so it will automatically get put into SD configs by Prometheus. 
Happy to help if there is a gap, maybe documentation could be helpful here.

**Comment by AlexsJones** [comment]
I'd ask you to try this out with  `v0.2.8` as the `K8sGPT` version

**Comment by AlexsJones** [comment]
Please reopen if needed
