### ISSUE TITLE
Error helm install

### ISSUE THREAD

**Issue by agvsap1** [k8sgpt-ai/k8sgpt-operator#90]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Host OS and its Version

GKE 1.25

### Steps to reproduce

Hi

When I am goint to install the system reports this error

helm install release k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace
Error: parse error at (k8sgpt-operator/templates/deployment.yaml:60): unclosed action

Regards.

### Expected behaviour

Hi

When I am goint to install the system reports this error

helm install release k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace
Error: parse error at (k8sgpt-operator/templates/deployment.yaml:60): unclosed action

Regards.

### Actual behaviour

Hi

When I am goint to install the system reports this error

helm install release k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace
Error: parse error at (k8sgpt-operator/templates/deployment.yaml:60): unclosed action

Regards.

### Additional Information

Hi

When I am goint to install the system reports this error

helm install release k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace
Error: parse error at (k8sgpt-operator/templates/deployment.yaml:60): unclosed action

Regards.

**Comment by AlexsJones** [comment]
Thank you for reporting this, what helm chart version is this for?

**Comment by agvsap1** [comment]
Hi

This is the version

NAME                    CHART VERSION   APP VERSION     DESCRIPTION
k8sgpt/k8sgpt-operator  0.0.13          0.0.13          Automatic SRE Superpowers within your Kubernete...

**Comment by AlexsJones** [comment]
Please try with the latest version
```
helm repo update 
helm install release k8sgpt/k8sgpt-operator -n k8sgpt-operator-system --create-namespace --version 0.0.14
```

**Comment by agvsap1** [comment]
Hi

I update my helm version, and now I can deploy the operator successfully.

Regards.
