### ISSUE TITLE
[Feature]: K8sgpt-deployment ownerref to operator

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#92]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

Adding an owner-reference from the k8sgpt-operator to the  deployment assets would help visualise it in argocd and flux

### Benefits

better visualisation

**Comment by arbreezy** [comment]
I will pick this up tomorrow , feel free to assign it to me @AlexsJones
