### ISSUE TITLE
Bug: empty analyze results when running with operator on AKS + error is raised

### ISSUE THREAD

**Issue by eyalsofer** [k8sgpt-ai/k8sgpt-operator#98]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v1alpha1

### Kubernetes Version

V 1.25.6

### Host OS and its Version

Ubunto 

### Steps to reproduce

1. install K8SGPT operator on AKS
2. run   kubectl get results -o json | jq .

### Expected behaviour

list with analyzed data is return + no error at k8sgpt deployment.

### Actual behaviour

returns empty list: 
{
  "apiVersion": "v1",
  "items": [],
  "kind": "List",
  "metadata": {
    "resourceVersion": ""
  }
}
+ error is raised: Error: AI provider openai not specified in configuration. Please run k8sgpt auth

### Additional Information

Spoke with Aris on this issue (Aris: "we've recently refactored the way we interact with k8sgpt service and I think we need to tweak it a bit")

**Comment by AlexsJones** [comment]
@eyalsofer how does it behave if you run this from the CLI rather than the operator?

**Comment by matthisholleville** [comment]
@AlexsJones The choice of the backend is not taken into account by the client API it seems.

**Comment by matthisholleville** [comment]
@AlexsJones The choice of backend is not supported by the client API it seems.

**Comment by AlexsJones** [comment]
> @AlexsJones The choice of backend is not supported by the client API it seems.

It should be as per K8sGPT code.
```
	clients = []IAI{
		&OpenAIClient{},
		&AzureAIClient{},
		&LocalAIClient{},
		&NoOpAIClient{},
	}
	Backends = []string{
		"openai",
		"localai",
		"azureopenai",
		"noopai",
	}
```

Unfortunately I cant test this without access ( I have applied )

**Comment by AlexsJones** [comment]
It looks to me like the engine is not being set correctly in the operator through to the client 
cc @arbreezy

**Comment by AlexsJones** [comment]
What do the logs say from the operator @eyalsofer ?

**Comment by AlexsJones** [comment]
Can you please try version 0.0.14 of the operator?

**Comment by eyalsofer** [comment]
ok i deleted the CRD and updated the helm chart of the operator to 0.0.14.
Still seeing errors - what do you mean by redeploy k8sgpt? maybe im missing a step. 
Here are pod's logs: 

2023-05-15T09:27:03Z    ERROR   Reconciler error        {"controller": "k8sgpt", "controllerGroup": "core.k8sgpt.ai", "controllerKind": "K8sGPT", "K8sGPT": {"name":"k8sgpt-sample","namespace":"kube-system"}, "namespace": "kube-system", "name": "k8sgpt-sample", "reconcileID": "1dd2277a-c121-494a-a506-a93a3e012b1f", "error": "failed to call Analyze RPC: rpc error: code = Unknown desc = AI provider not specified in configuration"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
Finished Reconciling K8sGPT with error: failed to call Analyze RPC: rpc error: code = Unknown desc = AI provider not specified in configuration
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
Finished Reconciling K8sGPT
E0515 09:32:27.151914       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.K8sGPT: the server could not find the requested resource (get k8sgpts.core.k8sgpt.ai)
W0515 09:32:28.139892       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.K8sGPT: the server could not find the requested resource (get k8sgpts.core.k8sgpt.ai)
E0515 09:32:28.139932       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.K8sGPT: failed to list *v1alpha1.K8sGPT: the server could not find the requested resource (get k8sgpts.core.k8sgpt.ai)

**Comment by AlexsJones** [comment]
What version of K8sGPT is in the CR? It needs to be at least v0.3.0

**Comment by eyalsofer** [comment]
yes, its v3.0:     
Image:         ghcr.io/k8sgpt-ai/k8sgpt:v0.3.0

**Comment by eyalsofer** [comment]
i see this errors in k8sgpt-operator-system ns:
Finished Reconciling K8sGPT with error: failed to call Analyze RPC: rpc error: code = Unknown desc = failed while calling AI provider azureopenai: error, status code: 401, message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
2023-05-15T10:25:36Z    ERROR   Reconciler error        {"controller": "k8sgpt", "controllerGroup": "core.k8sgpt.ai", "controllerKind": "K8sGPT", "K8sGPT": {"name":"k8sgpt-sample","namespace":"kube-system"}, "namespace": "kube-system", "name": "k8sgpt-sample", "reconcileID": "696c4957-62ae-47cd-8419-8cafc6d8e5f5", "error": "failed to call Analyze RPC: rpc error: code = Unknown desc = failed while calling AI provider azureopenai: error, status code: 401, message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}

**Comment by eyalsofer** [comment]
i will try to recreate the secret

**Comment by eyalsofer** [comment]
got the error again after recreating the secret

**Comment by AlexsJones** [comment]
Unfortunately, I am limited in assisting until I have access to the API, which could be weeks.

It would be helpful if you could reproduce this without the operator and just use K8sGPT CLI

**Comment by eyalsofer** [comment]
i tried yesterday the k8sgpt with openai token and it worked fine.
i'll try now with azureopnai

**Comment by eyalsofer** [comment]
btw, found a bug with the k8sgbt cli auth command:
k8sgpt auth --backend azureopenai --baseurl https://<your Azure OpenAI endpoint> --engine <deployment_name> --model <model_name>
it throws: Error: unknown flag: --backend
so i combined the engine after the baseurl and it worked.
its from the azure openai section here: https://github.com/k8sgpt-ai/k8sgpt

**Comment by eyalsofer** [comment]
reproduced the issue with the k8sgpt cli:
![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/120107188/5d6eee45-f959-4c54-9566-6e6ef3e131d4)

**Comment by arbreezy** [comment]
the auth cli argument has recently changed and we should reflect this in README file.

it looks like you haven't properly configured the provider, now you get a 404 instead of a 401

I believe @AlexsJones will be able to help with testing it in the operator and cli.

**Comment by AlexsJones** [comment]
If you update to `k8sgpt version 0.3.1` you can give this command:
```
k8sgpt auth new --backend azureopenai --baseurl <> --engine <> --model <>
```

It is a big clunky to work with the analyze by having to specify the backend, something I will look at improving

**Comment by eyalsofer** [comment]
i tried to remove azureopenai auth settings in order to set it up again: 
![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/120107188/b3a6d1e0-d127-407e-bd70-e0ca93866667)
However, I did manage to remove openai auth settings.

**Comment by AlexsJones** [comment]
I have tested this now in the operator.. 

```
kubectl apply -f - << EOF
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  model: gpt-35-turbo
  backend: azureopenai
  baseUrl: https://k8sgpt.openai.azure.com/
  engine: llm
  noCache: false
  version: v0.3.2
  enableAI: true
  secret:
    name: k8sgpt-sample-secret
    key: azure-api-key
EOF
```

I can confirm azureopenai as a backend is working cc @arbreezy 

![image](https://github.com/k8sgpt-ai/k8sgpt-operator/assets/1235925/a51eed95-bfeb-4b9b-bd95-1e5deba504d7)

**Comment by eyalsofer** [comment]
btw, this is the error im seeing:
Finished Reconciling K8sGPT with error: failed to call Analyze RPC: rpc error: code = Unknown desc = exhausted API quota for AI provider azureopenai: error, status code: 429, message: Requests to the Creates a completion for the chat message Operation under Azure OpenAI API version 2023-03-15-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 59 seconds.

**Comment by arbreezy** [comment]
hey  @eyalsofer as it states in the error message, you've reached your quota in Azure OpenAI API, this is unrelated to the operator's functionality check your Azure subscription please :)

**Comment by eyalsofer** [comment]
quick update: the logs of the k8sgpt-operator and k8sgpt-depoyment looks ok: 
k8sgpt-deployment:
{"level":"info","ts":1684669226.123519,"caller":"server/log.go:50","msg":"request completed","duration_ms":219,"method":"/schema.v1.Server/Analyze","request":"backend:\"azureopenai\" explain:true max_concurrency:10 output:\"json\"","remote_addr":"10.244.0.239:52994"}
{"level":"info","ts":1684669256.259569,"caller":"server/log.go:50","msg":"request completed","duration_ms":95,"method":"/schema.v1.Server/Analyze","request":"backend:\"azureopenai\" explain:true max_concurrency:10 output:\"json\"","remote_addr":"10.244.0.239:52994"}
k8sgpt-operator:
Checking if defaultk8sapiapp is still relevant
Checking if defaultk8sapiappdeployment is still relevant
Checking if defaultk8sapiappdeployment745688cf74p6wx9 is still relevant
Checking if defaultk8sapiappdeployment56c75f487z4xfh is still relevant
Checking if defaultk8sapiappdeployment745688cf74d4tpf is still relevant
Finished Reconciling K8sGPT

but the output of kubectl get results -o json | jq . still empty: 
{
  "apiVersion": "v1",
  "items": [],
  "kind": "List",
  "metadata": {
    "resourceVersion": ""
  }
}
@AlexsJones  - am I'm doing something wrong here?

**Comment by lioryantov** [comment]
Hi, I worked based on instructions provided on https://github.com/k8sgpt-ai/k8sgpt and also by watching Youtube by @AlexsJones  (https://www.youtube.com/watch?v=hb4du-oK0KY) in order to connect my AKS with Azure Open AI service. 
I installed the operator, while creating K8sGPT with version: v0.3.6 caused operator pod to print an error:
```
2023-06-08T11:28:15.604471896Z Finished Reconciling K8sGPT with error: failed to call Analyze RPC: rpc error: code = Unimplemented desc = unknown service schema.v1.Server
2023-06-08T11:28:15.604718611Z 2023-06-08T11:28:15Z	ERROR	Reconciler error	{"controller": "k8sgpt", "controllerGroup": "core.k8sgpt.ai", "controllerKind": "K8sGPT", "K8sGPT": {"name":"k8sgpt-azureopenai-new","namespace":"k8sgpt-operator-system"}, "namespace": "k8sgpt-operator-system", "name": "k8sgpt-azureopenai-new", "reconcileID": "efa43bfb-0739-4af3-94bc-be58c525458a", "error": "failed to call Analyze RPC: rpc error: code = Unimplemented desc = unknown service schema.v1.Server"}
2023-06-08T11:28:15.604738413Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
2023-06-08T11:28:15.604744713Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324
2023-06-08T11:28:15.604761514Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
2023-06-08T11:28:15.604766614Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265
2023-06-08T11:28:15.604771915Z sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
2023-06-08T11:28:15.604778315Z 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226
```
When I updated it to use v0.3.2, then Reconciling K8sGPT process was done successfully and I got Result was created.

**Comment by arbreezy** [comment]
Operator at the moment is compatible with 
<= v0.3.4 of k8sgpt, the error is expected thanks for flagging it.

**Comment by lioryantov** [comment]
@arbreezy Thank you for clarifying it.
